version: '3.9'

services:
  database:
    image: postgres
    environment:
      POSTGRES_URL: "jdbc:postgresql://localhost:5432/products-db"
      POSTGRES_DB: "products-db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

  flyway:
    image: flyway/flyway:10.21-alpine
    command: -url=jdbc:postgresql://database:5432/products-db -schemas=public -user=postgres -password=123456 -connectRetries=60 migrate
    volumes:
      - $PWD/src/main/resources/db/migration:/flyway/sql
    depends_on:
      - database
    networks:
      - postgres-network

  api:
    depends_on:
      - database
    build: .
    environment:
      DB_URL: "jdbc:postgresql://database:5432/products-db"
      SPRING_PROFILES_ACTIVE: "dev"
    ports:
      - "8080:8080"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge